package permlab.ui;

import permlib.Permutation;
import permlib.classes.InvolutionPermClass;
import permlib.classes.PermutationClass;
import permlib.classes.SimplePermClass;
import java.awt.*;
import java.util.*;
import javax.swing.*;
import permlib.classes.PermClassInterface;
import permlib.property.Simple;
import permlib.utilities.IOUtilities;

/**
 * Frame containing options to animate or enumerate a class of permutation with
 * specified properties.
 * 
 * @author M Albert
 */
public class ClassEnumerationFrame extends javax.swing.JFrame {

    private JFrame thisFrame;
    private ArrayList<SwingWorker> workerPool = new ArrayList<SwingWorker>();

    /**
     * Creates new form ClassEnumerationFrame
     */
    public ClassEnumerationFrame() {
        initComponents();
        thisFrame = this;
        // From http://stackoverflow.com/questions/286727/java-keylistener-for-jframe-is-being-unresponsive
        KeyboardFocusManager manager = KeyboardFocusManager.getCurrentKeyboardFocusManager();
        manager.addKeyEventDispatcher(new HelpDispatcher("Class window", "ClassFrameHelp.html", this));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actionButtonGroup = new javax.swing.ButtonGroup();
        formatButtonGroup = new javax.swing.ButtonGroup();
        controlPanel = new javax.swing.JPanel();
        basisPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        basisTextArea = new javax.swing.JTextArea();
        lengthField = new javax.swing.JTextField();
        lengthLabel = new javax.swing.JLabel();
        enumerateButton = new javax.swing.JButton();
        animateButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        restrictPanel = new javax.swing.JPanel();
        simplesCheckBox = new javax.swing.JCheckBox();
        involutionsCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        controlPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        controlPanel.setPreferredSize(new java.awt.Dimension(314, 500));

        basisPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Basis"));

        basisTextArea.setColumns(20);
        basisTextArea.setRows(5);
        basisTextArea.setToolTipText("Basis area. Enter one basis element per line.");
        jScrollPane1.setViewportView(basisTextArea);

        javax.swing.GroupLayout basisPanelLayout = new javax.swing.GroupLayout(basisPanel);
        basisPanel.setLayout(basisPanelLayout);
        basisPanelLayout.setHorizontalGroup(
            basisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basisPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
        );
        basisPanelLayout.setVerticalGroup(
            basisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basisPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addContainerGap())
        );

        lengthField.setText("1-12");
        lengthField.setToolTipText("Desired lengths. Can be a mix of ranges and single values, e.g. 3, 5, 7, 10-12.");

        lengthLabel.setText("Length");

        enumerateButton.setText("Enumerate");
        enumerateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doEnumeration(evt);
            }
        });

        animateButton.setText("Animate");
        animateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doAnimation(evt);
            }
        });

        stopButton.setText("Stop all");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        restrictPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Restrict to"));

        simplesCheckBox.setText("Simples");

        involutionsCheckBox.setText("Involutions");

        javax.swing.GroupLayout restrictPanelLayout = new javax.swing.GroupLayout(restrictPanel);
        restrictPanel.setLayout(restrictPanelLayout);
        restrictPanelLayout.setHorizontalGroup(
            restrictPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restrictPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(restrictPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(simplesCheckBox)
                    .addComponent(involutionsCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        restrictPanelLayout.setVerticalGroup(
            restrictPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restrictPanelLayout.createSequentialGroup()
                .addComponent(simplesCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(involutionsCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(basisPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(controlPanelLayout.createSequentialGroup()
                                .addComponent(restrictPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enumerateButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(animateButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(stopButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(controlPanelLayout.createSequentialGroup()
                                .addComponent(lengthLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lengthField)))))
                .addGap(6, 6, 6))
        );

        controlPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {animateButton, enumerateButton});

        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(basisPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lengthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lengthLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addComponent(enumerateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(animateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stopButton))
                    .addComponent(restrictPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(controlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Begins the enumeration of the class.
     * 
     * @param evt responds to the enumerate button being pressed
     */
    private void doEnumeration(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doEnumeration
        ClassEnumerationFrameTask task = new ClassEnumerationFrameTask(
                IOUtilities.getNumbers(lengthField.getText()),
                simplesCheckBox.isSelected(), involutionsCheckBox.isSelected(),
                basisTextArea.getText(), thisFrame);
        workerPool.add(task);
        task.execute();
    }//GEN-LAST:event_doEnumeration

    /**
     * Begins the animation of the class.
     * 
     * @param evt responds to the animate button being pressed
     */
    private void doAnimation(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doAnimation
        PermClassInterface theClass = getPermClassInterface();
        AnimationTask task;
        if (involutionsCheckBox.isSelected() && simplesCheckBox.isSelected()) {
            task = new AnimationTask(theClass, IOUtilities.getNumbers(lengthField.getText()), new Simple());
        } else {
            task = new AnimationTask(theClass, IOUtilities.getNumbers(lengthField.getText()));
        }
        workerPool.add(task);
        task.execute();
    }//GEN-LAST:event_doAnimation

    /**
     * Returns the underlying permutation class.
     * 
     * @return the underlying permutation class.
     */
    private PermClassInterface getPermClassInterface() {
        PermClassInterface theClass;
        Scanner in = new Scanner(basisTextArea.getText());
        ArrayList<Permutation> basis = new ArrayList<Permutation>();
        while (in.hasNextLine()) {
            basis.add(new Permutation(in.nextLine()));
        }
        if (involutionsCheckBox.isSelected()) {
            theClass = new InvolutionPermClass(basis);
        } else if (simplesCheckBox.isSelected()) {
            theClass = new SimplePermClass(basis);
        } else {
            theClass = new PermutationClass(basis);
        }
        return theClass;
    }

    /**
     * Cancels all tasks that have been started from this frame.
     * 
     * @param evt responds to the stop button being pressed.
     */
    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        for (SwingWorker task : workerPool) {
            task.cancel(true);
        }
    }//GEN-LAST:event_stopButtonActionPerformed

    /**
     * Cancels all threads created from this frame as window is closed.
     * 
     * @param evt responds to window closing
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        for (SwingWorker task : workerPool) {
            task.cancel(true);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassEnumerationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassEnumerationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassEnumerationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassEnumerationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ClassEnumerationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup actionButtonGroup;
    private javax.swing.JButton animateButton;
    private javax.swing.JPanel basisPanel;
    private javax.swing.JTextArea basisTextArea;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JButton enumerateButton;
    private javax.swing.ButtonGroup formatButtonGroup;
    private javax.swing.JCheckBox involutionsCheckBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lengthField;
    private javax.swing.JLabel lengthLabel;
    private javax.swing.JPanel restrictPanel;
    private javax.swing.JCheckBox simplesCheckBox;
    private javax.swing.JButton stopButton;
    // End of variables declaration//GEN-END:variables
    private StringBuilder outputText;

    /**
     * Checks whether the user input is of an appropriate form. That is, valid
     * permutations in the basis area and a positive integer in the length field.
     * 
     * @return true if the input is valid, false otherwise
     */
    private boolean wellFormattedInput() {
        if (!IOUtilities.isPermsString(basisTextArea.getText())) {
            JOptionPane.showMessageDialog(this,
                    "Improperly formatted basis.",
                    "Format error",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (!IOUtilities.isNumbersString(lengthField.getText())) {
            JOptionPane.showMessageDialog(this,
                    "Improperly formatted lengths.",
                    "Format error",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
}