package permlab.ui;

import javax.swing.*;

/**
 * Defines a text frame to display lists of permutations.
 * 
 * @author M Belton
 */
public class TableTextFrame extends JFrame {

    /**
     * Creates new form TableTextFrame
     */
    public TableTextFrame() {
        initComponents();
        setVisible(true);
    }

    public TableTextFrame(String str) {
        initComponents();
        textArea.setText(str);
        setVisible(true);
    }

    public TableTextFrame(Long[][] values) {
        initComponents();
        String contents = formattedInput(values);
        textArea.setText(contents);
        setVisible(true);
    }

    private String formattedInput(Long[][] values) {
        StringBuilder result = new StringBuilder();

        if (values[0].length == 1) {
            for (int i = 0; i < values.length - 1; i++) {
                result.append(values[i][0]).append(", ");
            }
            result.append(values[values.length - 1][0]);
        } else if (values.length == 1) {
            for (int i = 0; i < values[0].length - 1; i++) {
                result.append(values[0][i]).append(", ");
            }
            result.append(values[0][values[0].length - 1]);
        } else {
            int row = 0;
            while (row < values.length) {
                int col = 0;
                while (col < values[0].length - 1) {
                    result.append(values[row][col]).append(",\t");
                    col++;
                }
                result.append(values[row][values[0].length - 1]).append("\n");
                row++;
            }
        }
        return result.toString();
    }

    public JTextArea getTextArea() {
        return this.textArea;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textPane = new JScrollPane();
        textArea = new JTextArea();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        textArea.setColumns(20);
        textArea.setRows(5);
        textPane.setViewportView(textArea);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(textPane, GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(textPane, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | UnsupportedLookAndFeelException | IllegalAccessException | InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableTextFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableTextFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JTextArea textArea;
    private JScrollPane textPane;
    // End of variables declaration//GEN-END:variables
}
