package permlab.ui;

import javax.swing.JTextArea;

/**
 * Defines a text frame to display lists of permutations.
 * 
 * @author M Belton
 */
public class TableTextFrame extends javax.swing.JFrame {

    /**
     * Creates new form TableTextFrame
     */
    public TableTextFrame() {
        initComponents();
        setVisible(true);
    }

    public TableTextFrame(String str) {
        initComponents();
        textArea.setText(str);
        setVisible(true);
    }

    public TableTextFrame(Long[][] values) {
        initComponents();
        String contents = formattedInput(values);
        textArea.setText(contents);
        setVisible(true);
    }

    private String formattedInput(Long[][] values) {
        StringBuilder result = new StringBuilder();

        if (values[0].length == 1) {
            for (int i = 0; i < values.length - 1; i++) {
                result.append(values[i][0] + ", ");
            }
            result.append(values[values.length - 1][0]);
        } else if (values.length == 1) {
            for (int i = 0; i < values[0].length - 1; i++) {
                result.append(values[0][i] + ", ");
            }
            result.append(values[0][values[0].length - 1]);
        } else {
            int row = 0;
            while (row < values.length) {
                int col = 0;
                while (col < values[0].length - 1) {
                    result.append(values[row][col] + ",\t");
                    col++;
                }
                result.append(values[row][values[0].length - 1] + "\n");
                row++;
            }
        }
        return result.toString();
    }

    public JTextArea getTextArea() {
        return this.textArea;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textPane = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        textArea.setColumns(20);
        textArea.setRows(5);
        textPane.setViewportView(textArea);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(textPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, textPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableTextFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableTextFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableTextFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableTextFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableTextFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea textArea;
    private javax.swing.JScrollPane textPane;
    // End of variables declaration//GEN-END:variables
}
